---
version: '3.8' # optional
services:
  pg_db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=stage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  init_db:
    image: flyway/flyway:7.11-alpine
    depends_on:
      - pg_db
    volumes:
      - ./db_scripts:/flyway/sql
    command: -url=jdbc:postgresql://pg_db:5432/stage -user=postgres -password=secret migrate

volumes:
  pg_project:
...
